@startuml
title SmartHome HeatingService Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

class HeatingScenarioService {
    +HeatingScenarioDto saveScenario(HeatingScenarioDto scenario)
    +HeatingScenarioDto getScenario(Long id)
    +HeatingScenarioDto updateScenario(Long id, HeatingScenarioDto scenario)
    +HeatingScenarioDto enableScenario(Long id)
    +HeatingScenarioDto disableScenario(Long id)
    +void scheduledAllScenaries() //запуск всех задач по их расписанию
}

class HeatingScenario {
  +Long id
  +Long heatingId
  +Enum type
  +String cron
}

class Heating {
  +Long id
  +boolean isOn
  +Double targetTemperature
  +Double currentTemperature
}

HeatingScenarioService -- HeatingScenario : use
HeatingScenario "1" -- "0..*" Heating : has


@enduml