@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(customer, "Клиент", "Пользователь системы отопления")

System_Boundary(monolith, "Система контроля отоплением") {
    Container(server, "Сервер", "Java Backend", "Управляет логикой управления отоплением и взаимодействует с датчиками")
    Container(sensor, "Температурный датчик", "Temperature Sensor", "Мониторит температуру и отвечает на запросы сервера")
}

Rel(customer, server, "Использует")
Rel(server, sensor, "Отправляет команды и запрашивает данные о температуре")

@enduml
