@startuml
!theme bluegray
!define RECTANGLE #dddddd
!define CIRCLE #8dd3c7

rectangle "Kafka Message Broker" as Kafka CIRCLE


rectangle "API Gateway" as APIGW RECTANGLE
rectangle "Heating Control Service" as HeatingControl RECTANGLE
rectangle "Temperature Monitoring Service" as TempMonitor RECTANGLE
rectangle "Device Management Service" as DeviceManagement RECTANGLE
rectangle "User Management Service" as UserManagement RECTANGLE
rectangle "Notification Service" as Notification RECTANGLE
rectangle "Scenario Management Service" as Scenario RECTANGLE
database "Database (User)" as UserDB
database "Database (Temperature)" as TempDB
database "Database (Device)" as DeviceDB

APIGW -down-> HeatingControl : API Calls
APIGW -down-> TempMonitor : API Calls
APIGW -down-> DeviceManagement : API Calls


APIGW -down-> UserManagement : API Calls
APIGW -down-> Notification : API Calls
APIGW -down-> Scenario : API Calls

TempMonitor -down-> Kafka : Publish Temperature Updates
HeatingControl -down-> Kafka : Subscribe Temperature Updates
Notification -down-> Kafka : Subscribe to Notifications
DeviceManagement -down-> Kafka : Publish Device Events

UserManagement -down-> UserDB : Read/Write User Data
TempMonitor -down-> TempDB : Store Temperature Data
DeviceManagement -down-> DeviceDB : Store Device Data
@enduml
