@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

skinparam wrapWidth 300
LAYOUT_WITH_LEGEND()


Person(user, "Клиент", "Пользователь системы умного дома")
Person(admin, "Администратор", "Администратор системы умного дома")

Boundary(home, "Дом") {
    System_Ext(device, "Устройство", "Устройство системы умного дома")
    System_Ext(sensor, "Датчик", "Датчик системы умного дома")
    System(hub, "Gateway умного дома", "Хаб для устройств и датчиков")
}

Container(web, "Web приложение", "React", "Регистрация новых устройств, изменение параметров устройств, просмотр параметров телеметрии")
Container(mobileApp, "Мобильное приложение", "Flutter", "Регистрация новых устройств, изменение параметров устройств, просмотр параметров телеметрии")
Container(webAdmin, "Web приложение администора", "React", "Управление пользователями, ролями, устройствами, датчиками")

System_Boundary(system, "Сервер") {
    Container(users, "Микросервис управления клиентами", "Python")
    Container(devices, "Микросервис управления устройствами", "Python")
    Container(telemetry, "Микросервис телеметрии", "Python")
    Container(gateway, "API Gateway", "Kong", "Обработка и маршрутизация запросов")
    ContainerDb(db_users, "База данных для Микросервиса Клиентов", "PostgreSQL")
    ContainerDb(db_devices, "База данных для Микросервиса Устройств", "PostgreSQL")
    ContainerDb(db_telemetry, "База данных для Микросервиса телеметрии", "PostgreSQL")
}

Rel(users, db_users, "Запись \ Чтение данных", "SQL \ TCP")
Rel(devices, db_devices, "Запись \ Чтение данных" , "SQL \ TCP")
Rel(telemetry, db_telemetry, "Запись \ Чтение данных" , "SQL \ TCP")

Rel(user, web, "Использует систему")
Rel(user, mobileApp, "Использует систему")
Rel(admin, webAdmin, "Использует систему")

Rel(web, gateway, "Взаимодействует с системой", "HTTPS, JSON")
Rel(mobileApp, gateway, "Взаимодействует с системой", "HTTPS, JSON")
Rel(webAdmin, gateway, "Взаимодействует с системой", "HTTPS, JSON")

Rel(gateway, users, "Просмотр профиля, изменение профиля")
Rel(gateway, devices, "Просмотр устройств, изменение параметров устройства, добавление новых устройств")
Rel(gateway, telemetry, "Просмотр параметров телеметрии")

Rel(hub, device, "Обновление параметров")
Rel(sensor, hub, "Передача показаний")
Rel(hub, gateway, "Взаимодействует с системой", "HTTPS, JSON")


@enduml