@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Пользователь", "Пользователь у которого находятся датчики")
Person(device, "Устройство", "Датчик по мониторингу и устройство по управлению отоплением")
System(system, "Приложение", "Позволяет управлять отоплением пользователям и собирать информацию с датчиков")

Rel(user, system, "Управление отоплением", "Включение, отключение отопления и просмотр температуры")
Rel(system, device, "Запрос", "Запрос температуры и установка температуры")
@enduml
