@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Пользователь", "Пользователь мобильного приложения")

System_Boundary(system_boundary, "Экосистема умной деревни") {

    Container(mobileApp, "Мобильное приложение", "iOS/Android", "Позволяет пользователям управлять оборудованием и просматривать данные о состоянии дома")
    Container(apiGateway, "API Gateway", "API Gateway", "Обрабатывает все входящие запросы и маршрутизирует их к серверу")
    Container(server, "Сервер", "Сервис бэкенда", "Обрабатывает запросы от моб. приложения, взаимодействует с базой данных, управляет электро-оборудованием и читает события из Kafka")
    ContainerDb(database, "База данных", "SQL-база данных", "Хранит данные пользователей и данные системы умного дома")
    Container(messageQueue, "Kafka", "Брокер сообщений", "Обрабатывает события от датчиков и электро-оборудования")

    System_Ext(heatingEquipment, "Интерфейс электро-оборудования (котлы, фонари, ворота, камеры и т.д)", "Получает команды для включения/выключения и отправляет события в Kafka")
    System_Ext(temperatureSensor, "Интерфейс датчика в доме", "Отправляет данные о состоянии дома (температура, влажность, движение, уровень освещённости) в Kafka")
}

Rel(user, mobileApp, "Использует")
Rel(mobileApp, apiGateway, "Отправляет запросы", "HTTP")
Rel(apiGateway, server, "Маршрутизирует запросы", "HTTP")
Rel(server, database, "Читает и записывает данные", "SQL")
Rel(server, heatingEquipment, "Отправляет команды по HTTP", "Включить/Выключить и т.д.")
Rel(heatingEquipment, messageQueue, "Отправляет события", "Kafka")
Rel(temperatureSensor, messageQueue, "Публикует данные о состоянии", "Kafka")
Rel(server, messageQueue, "Читает события", "Kafka")
Rel(mobileApp, apiGateway, "Управление отоплением", "HTTP")
Rel(mobileApp, apiGateway, "Вкл./выкл. свет", "HTTP")
Rel(mobileApp, apiGateway, "Закр./откр. ворота", "HTTP")
Rel(mobileApp, apiGateway, "Наблюдение за домом", "HTTP")
Rel(mobileApp, apiGateway, "Будущее неуточнённое поведение", "HTTP")

@enduml
