@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь устройства")

Container(gateway, "API Gateway", "NodeJS")
Container(queue, "Queue", "Kafka")

Container_Boundary(clients, "Микросервис по управлению данными клиентов", "NodeJS") {
    Component(httpController, "Контроллер для входящих запросов", "", "Обрабатывает HTTP запросы для пользователя, дома и связей устройств с домом")
    Component(clientController, "Контроллер по управлению данными пользователя", "", "Добавляет пользователей, дома и привязывает устройства к дому")
    Component(queueInController, "Контроллер для записи сообщений в очередь")

    Rel(httpController, clientController, "Вызов методов")
    Rel(clientController, queueInController, "Вызов методов")
}

ContainerDb(db_clients, "Data Base для устройств", "PostgreSQL", "Хранит данные пользователя, дома")

Rel(user, gateway, "Просмотр и изменение данных", "Просмотр и изменение данных пользователя, дома")

Rel(gateway, httpController, "Маршрутизация")

Rel(clientController, db_clients, "Сохранение данных пользователя")

Rel(queueInController, queue, "Отправка сообщений о регистрации и привязывании устройств")
@enduml
